name: Release & Publish
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    outputs:
      version_changed: ${{ steps.release.outputs.version_changed }}
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Python Setup
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - id: release
        name: Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pip install python-semantic-release
          version_changed=$(semantic-release version | grep -q "The next version" && echo "true" || echo "false")
          echo "version_changed=$version_changed" >> "$GITHUB_OUTPUT"

  publish:
    needs: release
    if: needs.release.outputs.version_changed == 'true'
    runs-on: ubuntu-latest
    environment:
      name: pypi
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - run: |
          python -m pip install build
          python -m build
      - uses: pypa/gh-action-pypi-publish@release/v1
