name: Release & Publish
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    environment:
      name: pypi
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Python Setup
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Release and Publish
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pip install python-semantic-release build
          semantic-release publish
