name: Release & Publish
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    environment:
      name: pypi
      url: https://pypi.org/p/uvrun_simonb97
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_TOKEN }}

      - name: Python Setup
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Release and Publish
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          pip install python-semantic-release
          git config --global user.name "github-actions"
          git config --global user.email "action@github.com"
          semantic-release publish
